const QC_DATA = {
  asOf: "August 2026",
  kpis: [
    {
      label: "Top verified logical qubits",
      value: "96",
      detail: "QuEra · Nature, Jan 2026",
    },
    {
      label: "Best encoding ratio",
      value: "2:1",
      detail: "Quantinuum Helios color + Iceberg",
    },
    {
      label: "Peak 2Q gate fidelity",
      value: "99.99%",
      detail: "IonQ EQC · SQC silicon spin",
    },
    {
      label: "Below-threshold QEC",
      value: "Yes",
      detail: "Google Willow surface code, Dec 2024",
    },
  ],
  logicalRace: {
    labels: [
      "Feb 2024",
      "Apr 2024",
      "Nov 2024",
      "Dec 2024",
      "Nov 2025",
      "Dec 2025",
      "Jan 2026",
    ],
    series: [
      {
        label: "QuEra",
        color: "#7CFFB2",
        data: [null, null, null, null, null, null, 96],
      },
      {
        label: "Quantinuum",
        color: "#6EE7FF",
        data: [null, 4, 4, 4, 48, 48, 48],
      },
      {
        label: "Atom + Microsoft",
        color: "#C4A1FF",
        data: [null, null, 24, 24, 24, 24, 24],
      },
      {
        label: "Infleqtion",
        color: "#FFD166",
        data: [null, null, null, null, null, 12, 12],
      },
      {
        label: "Google Willow",
        color: "#FF7AD9",
        data: [null, null, null, 1, 1, 1, 1],
      },
      {
        label: "Nord Quantique",
        color: "#9BB0FF",
        data: [1, 1, 1, 1, 1, 1, 1],
      },
    ],
  },
  leaderboard: [
    {
      rank: 1,
      company: "QuEra Computing",
      system: "Neutral-atom logical processor",
      logical: 96,
      physical: 448,
      ratio: 4.7,
      qec: "[[16,6,4]] high-rate code",
      modality: "Neutral atom",
      when: "Jan 2026",
    },
    {
      rank: 2,
      company: "Quantinuum",
      system: "Helios",
      logical: 48,
      physical: 98,
      ratio: 2.0,
      qec: "Color code + Iceberg",
      modality: "Trapped ion",
      when: "Nov 2025",
    },
    {
      rank: 3,
      company: "Atom Computing + Microsoft",
      system: "Phoenix",
      logical: 24,
      physical: 1180,
      ratio: 49.2,
      qec: "Bacon-Shor",
      modality: "Neutral atom",
      when: "Nov 2024",
    },
    {
      rank: 4,
      company: "Infleqtion",
      system: "Sqale",
      logical: 12,
      physical: 1600,
      ratio: 133,
      qec: "Surface code",
      modality: "Neutral atom",
      when: "Dec 2025",
    },
    {
      rank: 5,
      company: "Google Quantum AI",
      system: "Willow",
      logical: 1,
      physical: 105,
      ratio: 105,
      qec: "Surface code (below threshold)",
      modality: "Superconducting",
      when: "Dec 2024",
    },
    {
      rank: 6,
      company: "Nord Quantique",
      system: "GKP cavity",
      logical: 1,
      physical: 1,
      ratio: 1,
      qec: "Bosonic GKP",
      modality: "Bosonic",
      when: "Feb 2024",
    },
  ],
  hardware: [
    {
      company: "QuEra",
      system: "Logical atom array",
      modality: "Neutral atom",
      headline: "Largest verified logical count",
      stats: [
        ["Logical qubits", "96"],
        ["Physical atoms", "448"],
        ["Encoding", "4.7 : 1"],
      ],
      note: "High-rate codes, not surface-code overhead. Published Jan 2026.",
    },
    {
      company: "Quantinuum",
      system: "Helios",
      modality: "Trapped ion",
      headline: "Best encoding efficiency",
      stats: [
        ["Logical qubits", "48"],
        ["Physical ions", "98"],
        ["2Q fidelity", "99.92%"],
      ],
      note: "All-to-all connectivity. Highest-accuracy commercial-class machine.",
    },
    {
      company: "Google",
      system: "Willow",
      modality: "Superconducting",
      headline: "Below-threshold surface code",
      stats: [
        ["Physical qubits", "105"],
        ["T1", "~100 µs"],
        ["QEC", "d=3 → d=7"],
      ],
      note: "Logical error halved as code distance grew. The threshold proof.",
    },
    {
      company: "IBM",
      system: "Heron / Kookaburra path",
      modality: "Superconducting",
      headline: "Enterprise scale + qLDPC",
      stats: [
        ["Condor (2023)", "1,121 q"],
        ["Starling target", "200 LQ / 2029"],
        ["Focus", "Utility + modular"],
      ],
      note: "Quality-first Heron line; Kookaburra qLDPC memory on the 2026 roadmap.",
    },
    {
      company: "IonQ",
      system: "Tempo / Forte",
      modality: "Trapped ion",
      headline: "Four-nines gates + revenue",
      stats: [
        ["2Q fidelity", "99.99%"],
        ["Algo. qubits", "64 (Tempo)"],
        ["FY2025 rev.", "$130M"],
      ],
      note: "First quantum company past $100M GAAP revenue (reported 2026).",
    },
    {
      company: "Atom Computing",
      system: "Phoenix",
      modality: "Neutral atom",
      headline: "1,180-site array + Microsoft",
      stats: [
        ["Logical qubits", "24"],
        ["Physical", "1,180"],
        ["Code", "Bacon-Shor"],
      ],
      note: "Early multi-logical entanglement. Magne target ~50 LQ late 2026.",
    },
  ],
  fidelity: [
    { label: "IonQ", value: 99.99, modality: "Trapped ion" },
    { label: "SQC", value: 99.99, modality: "Silicon spin" },
    { label: "Quantinuum", value: 99.92, modality: "Trapped ion" },
    { label: "Diraq", value: 98.92, modality: "Silicon spin" },
  ],
  eras: [
    {
      name: "NISQ",
      range: "2017–now",
      status: "Active",
      text: "Noisy intermediate-scale machines still dominate cloud access. Useful for research, benchmarking, and error-mitigated experiments — not general algorithms.",
    },
    {
      name: "Encoded NISQ",
      range: "2024–2027",
      status: "Now",
      text: "Logical qubits exist, but counts, lifetimes, and universal gate sets are still limited. The race is encoding overhead and real-time decoding.",
    },
    {
      name: "Early FTQC",
      range: "~2027–2033",
      status: "Approaching",
      text: "100+ reliable logical qubits is the near-term industrial prize. DARPA QBI aims to validate utility-scale systems by 2033.",
    },
    {
      name: "CRQC risk",
      range: "2030s (uncertain)",
      status: "Watch",
      text: "Cryptographically relevant machines remain a timeline, not a product. NIST PQC standards (2024) are the practical response today.",
    },
  ],
  timeline: [
    {
      year: "1981",
      era: "Theory",
      title: "Feynman proposes quantum simulation",
      text: "Classical computers cannot efficiently simulate quantum physics — build a quantum computer instead.",
    },
    {
      year: "1994",
      era: "Theory",
      title: "Shor’s algorithm",
      text: "Exponential speedup for factoring. RSA becomes a long-term quantum risk.",
    },
    {
      year: "1996",
      era: "Theory",
      title: "Quantum error correction",
      text: "Shor and Steane show quantum information can be protected. Fault tolerance becomes a research program.",
    },
    {
      year: "2016",
      era: "Cloud",
      title: "IBM Quantum Experience",
      text: "Real processors on the public cloud. Quantum stops being lab-only.",
    },
    {
      year: "2019",
      era: "Supremacy",
      title: "Google Sycamore",
      text: "53-qubit random circuit sampling. First widely cited quantum supremacy claim.",
    },
    {
      year: "2023",
      era: "Scale",
      title: "IBM Condor & Atom 1,180",
      text: "Physical counts cross 1,000. Quality vs. quantity debate intensifies.",
    },
    {
      year: "Dec 2024",
      era: "Logical",
      title: "Google Willow below threshold",
      text: "Larger surface-code distance lowers logical error. Threshold theorem, experimentally.",
    },
    {
      year: "Nov 2025",
      era: "Logical",
      title: "Quantinuum Helios · 48 LQ",
      text: "98 barium ions, ~2:1 encoding, 99.92% two-qubit gates.",
    },
    {
      year: "Jan 2026",
      era: "Logical",
      title: "QuEra · 96 LQ in Nature",
      text: "448 atoms, [[16,6,4]] high-rate code, 4.7:1 overhead.",
    },
    {
      year: "2026",
      era: "Industry",
      title: "Commercialization wave",
      text: "IonQ >$100M revenue; Quantinuum IPO path; Infleqtion listing; DARPA QBI Stage B.",
    },
  ],
  roadmap: [
    {
      when: "Late 2026",
      who: "Atom + Microsoft + QuNorth Magne",
      what: "Target ~50 logical qubits",
    },
    {
      when: "2026–27",
      who: "IBM Kookaburra",
      what: "qLDPC memory + LPUs; longer useful circuits",
    },
    {
      when: "2027",
      who: "Quantinuum / Pasqal / QuEra",
      what: "Race to 100+ logical qubits",
    },
    {
      when: "2029",
      who: "IBM Starling",
      what: "200 logical qubits on public superconducting roadmap",
    },
    {
      when: "2033",
      who: "DARPA QBI",
      what: "Utility-scale validation across 11 Stage B teams",
    },
  ],
  applications: [
    {
      name: "Quantum chemistry",
      score: 42,
      status: "Early utility experiments",
      text: "Small molecules and model Hamiltonians. Fault-tolerant chemistry still needs many more logical qubits and T gates.",
    },
    {
      name: "Optimization",
      score: 35,
      status: "Heuristic / annealer niche",
      text: "Annealing (D-Wave class) is commercially used; gate-model advantage on combinatorial problems is still contested.",
    },
    {
      name: "Quantum machine learning",
      score: 22,
      status: "Research",
      text: "Plenty of papers, little proven advantage. Encoding classical data remains expensive.",
    },
    {
      name: "Cryptanalysis (Shor)",
      score: 8,
      status: "Not yet",
      text: "Factoring 15 is a demo. Breaking RSA-2048 needs thousands of high-quality logical qubits.",
    },
    {
      name: "Post-quantum crypto",
      score: 78,
      status: "Standards live",
      text: "NIST PQC (2024) is the real 2026 security story. Migrate now; don’t wait for CRQC.",
    },
    {
      name: "Simulation / materials",
      score: 38,
      status: "Promising path",
      text: "Closest long-term product-market fit if logical counts keep compounding through 2029.",
    },
  ],
};
